### ISSUE TITLE
can't unload dplyr, ergo can't find function '%>%'?

### ISSUE THREAD

**Issue by avalonceleste** [Aariq/holodeck#9]
![screen shot 2019-02-21 at 12 57 36 pm](https://user-images.githubusercontent.com/47865720/53190959-afca7580-35d8-11e9-9b6b-93e69d8e7614.png)

I already uninstalled and reinstalled after the 'ropls' bug fix (which BY THE WAY I think it should also accept 'y' as an answer).

**Comment by Aariq** [comment]
It seems like this might be a bug in library(). https://github.com/tidyverse/tidyverse/issues/70  I'm about to upgrade R, so I'll have to re-install stuff anyways and I can see if this also happens to me

**Comment by Aariq** [comment]
I can't reproduce this on my machine.  Did you get it to work ever?  Maybe try running library(dplyr) again or try loading dplyr before loading tidymvsim?

**Comment by avalonceleste** [comment]
Switching the order of library() seemed to fix it... Or maybe it was restarting R that fixed it... Nonetheless, it's fixed!
